### ISSUE TITLE
Player stuck in tele on dm4 (teleporting continuously)

### ISSUE THREAD

**Issue by liback** [deurk/mvdsv#30] opened 2018-04-04 08:26 UTC
[teleportersarefun.zip](https://github.com/deurk/mvdsv/files/1874845/teleportersarefun.zip)
Reported by bgnr on Discord
Happened on london badplace server and for several players. It's as if they're exiting and entering continously when going into the teleporter with no way of leaving (except for /kill). See attached demo.

**Comment by liback** [comment] 2018-04-04 08:27
ping @meag

**Comment by mushis** [comment] 2018-04-04 08:28
![image](https://user-images.githubusercontent.com/3011167/38296848-87d6bff8-37ea-11e8-84db-d4da8cae14f9.png)

**Comment by molgrum** [comment] 2018-04-04 08:38
How do I reproduce this? @liback

**Comment by liback** [comment] 2018-04-04 08:50
Don't know how to provoke it as it seems they just entered the teleporter in the usual way. Maybe it depends on server uptime or something?

Technical prerequisites are however a recent enough ezQuake that supports protocol extensions (cl_pext_floatcoords 1) from Meag's fork otherwise you won't be able to connect to london badplace server where it happened. I guess it may be likely that the bug is related to the protocol extensions too, but who knows.

**Comment by VVD** [comment] 2018-04-04 09:34
Hot_Error: Server returned version 826562125, not 28
You probably need to upgrade.
Check http://www.quakeworld.net/

But I can connect to london badplace.

**Comment by meag** [comment] 2018-04-04 09:49
I can't replicate the problem on badplace right now, can anyone else?

I also suspect the protocol extensions... skurk (who recorded the demo) doesn't have the lag teleport extension enabled though, so I'm not sure how that would have affected it.

Were bots enabled?  Or recently toggled off?  When bots are enabled all objects (including teleport triggers) are increased in size as they are used for markers in bot navigation - then it checks the bounds of the object and doesn't execute standard trigger_touch() logic if touching the extended region.

I can replicate this locally by enabling bots then manually setting `k_fb_enabled 0` (doing it through the `botcmd disable` should reload the map).  I have `set k_fb_enabled 0` in server.cfg, I'm guessing there must be a way for that to be executed without the map being reloaded?..

**Comment by meag** [comment] 2018-04-04 10:07
Okay it's really simple.

Enable bots on dm4 (or the server's default map), disconnect from server.
KTX realises everyone has left, and executes `configs/reset.cfg`
`reset.cfg` executes `server.cfg`, which disables bots by default
The map is not reloaded, instead a default-map checker is created
That checker event does nothing, because dm4 is the server's default map, and we're not in intermission
(time passes)
Players connect to server, go through teleports, get bug

Map reload fixes it, but this path doesn't reset the flag.  I'll change KTX so it reloads the map if that variable is changed from how the map was loaded.

**Comment by meag** [comment] 2018-04-04 13:30
Closing: should be fixed by https://github.com/deurk/ktx/commit/b5e1ec0e05468dd4e4a8ce29fc910665291efe7a

**Closed by meag** 2018-04-04 13:30 UTC
